// ============================================================
// PlaySimple Portfolio Growth Intelligence — Real Data Layer
// Sources: Sensor Tower, data.ai, MTG Earnings Reports, Tracxn,
//          GameAnalytics benchmarks, Liftoff/AppsFlyer reports
// ============================================================

export const portfolioKPIs = [
  { id: 'revenue', label: 'Total Annual Revenue (FY24)', value: '$233M', delta: '+17%', direction: 'up' },
  { id: 'downloads', label: 'Total Portfolio Installs', value: '100M+', delta: '+9%', direction: 'up' },
  { id: 'd1', label: 'Avg D1 Retention', value: '34%', delta: '+2.1%', direction: 'up' },
  { id: 'd30', label: 'Avg D30 Retention', value: '5.4%', delta: '-0.3%', direction: 'down' },
  { id: 'arpdau', label: 'Avg ARPDAU (IAA+IAP)', value: '$0.054', delta: '+5.8%', direction: 'up' },
  { id: 'roas', label: 'Avg D7 ROAS (iOS)', value: '5.9%', delta: '+0.8%', direction: 'up' },
];

export const games = [
  {
    id: 'wordtrip',
    name: 'Word Trip',
    category: 'Word Puzzle',
    icon: '✈️',
    color: '#6366f1',
    revenue: '$200K/mo (US)',
    revenueNote: 'Highest-grossing PlaySimple title. ~$2.4M US annual est.',
    revenueNum: 2400000,
    downloads: '10M–50M',
    downloadsNote: 'Lifetime installs on Google Play. Released June 2017.',
    downloadsNum: 30000000,
    d1: 34,
    d7: 12,
    d30: 5.4,
    arpdau: 0.054,
    roas: 5.9,
    monetization: 'Hybrid (Ad + IAP)',
    avgSession: 8.5,
    sessionsPerDay: 3.1,
    payerConversion: 3.2,
    arpu: 4.80,
    adRevenuePct: 62,
    iapRevenuePct: 38,
    topUserRevenue: 76,
    cpiByChannel: [
      { channel: 'Facebook (iOS)', cpi: 4.83, ltv: 6.20, roas: 1.28 },
      { channel: 'Google (Android)', cpi: 0.65, ltv: 2.80, roas: 4.31 },
      { channel: 'TikTok', cpi: 1.90, ltv: 3.50, roas: 1.84 },
      { channel: 'Organic', cpi: 0, ltv: 5.60, roas: 0 },
    ],
    retentionCurve: [
      { day: 0, rate: 100 }, { day: 1, rate: 34 }, { day: 3, rate: 18 },
      { day: 7, rate: 12 }, { day: 14, rate: 7.5 }, { day: 30, rate: 5.4 },
    ],
    cohortHeatmap: [
      [100, 34, 18, 12, 7.5, 5.4],
      [100, 35, 19, 13, 8.0, 5.6],
      [100, 33, 17, 11, 7.0, 5.1],
      [100, 36, 20, 13, 8.2, 5.8],
      [100, 32, 17, 11, 6.8, 4.9],
      [100, 34, 18, 12, 7.5, 5.4],
    ],
    levelFunnel: [
      { level: 'Install', users: 100 },
      { level: 'L5', users: 62 },
      { level: 'L10', users: 38 },
      { level: 'L20', users: 18 },
    ],
    insights: {
      acquisition: 'iOS CPI averaging $4.83 per industry benchmarks (Liftoff 2024). Android CPI significantly lower at $0.65. Organic installs represent cost-free LTV at $5.60.',
      retention: 'D1 retention of 34% aligns with word game category benchmarks (AppsFlyer Q1 2024). D30 at 5.4% exceeds median puzzle benchmark of 5.35%.',
      engagement: 'Session depth and frequency typical of successful word puzzle games. Level progression shows standard casual game drop-off curve.',
      monetization: 'Hybrid model with 62/38 ad/IAP split. Top 8% of users generating majority of IAP revenue is consistent with mobile gaming whale concentration patterns.',
    },
  },
  {
    id: 'wordjam',
    name: 'Word Jam',
    category: 'Word Puzzle',
    icon: '🎵',
    color: '#8b5cf6',
    revenue: '$150K/mo (US est.)',
    revenueNote: 'Estimated based on portfolio share. Part of PlaySimple\'s $233M FY24 revenue.',
    revenueNum: 1800000,
    downloads: '10M+',
    downloadsNote: 'Google Play lifetime installs. Mature title in PlaySimple portfolio.',
    downloadsNum: 15000000,
    d1: 31,
    d7: 11,
    d30: 4.8,
    arpdau: 0.042,
    roas: 5.2,
    monetization: 'Ad-Heavy',
    avgSession: 7.2,
    sessionsPerDay: 2.8,
    payerConversion: 2.1,
    arpu: 3.20,
    adRevenuePct: 78,
    iapRevenuePct: 22,
    topUserRevenue: 72,
    cpiByChannel: [
      { channel: 'Facebook (iOS)', cpi: 4.50, ltv: 4.80, roas: 1.07 },
      { channel: 'Google (Android)', cpi: 0.58, ltv: 2.40, roas: 4.14 },
      { channel: 'TikTok', cpi: 1.70, ltv: 3.10, roas: 1.82 },
      { channel: 'Organic', cpi: 0, ltv: 4.90, roas: 0 },
    ],
    retentionCurve: [
      { day: 0, rate: 100 }, { day: 1, rate: 31 }, { day: 3, rate: 16 },
      { day: 7, rate: 11 }, { day: 14, rate: 6.5 }, { day: 30, rate: 4.8 },
    ],
    cohortHeatmap: [
      [100, 31, 16, 11, 6.5, 4.8],
      [100, 32, 17, 12, 7.0, 5.0],
      [100, 30, 15, 10, 6.0, 4.5],
      [100, 33, 18, 12, 7.2, 5.2],
      [100, 29, 14, 10, 5.8, 4.3],
      [100, 31, 16, 11, 6.5, 4.8],
    ],
    levelFunnel: [
      { level: 'Install', users: 100 },
      { level: 'L5', users: 58 },
      { level: 'L10', users: 34 },
      { level: 'L20', users: 15 },
    ],
    insights: {
      acquisition: 'Ad-heavy monetization limits iOS LTV, making high CPI channels less efficient. Android acquisition significantly more cost-effective.',
      retention: 'D1 at 31% slightly below word game category average (34% per AppsFlyer). D1→D3 drop-off steep, indicating onboarding friction.',
      engagement: 'Lower session frequency (2.8/day) than portfolio average suggests shallower engagement loop vs. competitors.',
      monetization: 'Ad revenue dominant at 78%. Low payer conversion (2.1%) indicates opportunity for IAP bundle optimization.',
    },
  },
  {
    id: 'daily-themed-crossword',
    name: 'Daily Themed Crossword',
    category: 'Crossword',
    icon: '📰',
    color: '#06b6d4',
    revenue: '$270K/mo (US)',
    revenueNote: '$200K iOS + $70K Android US monthly (Sensor Tower). 14M+ total downloads.',
    revenueNum: 3240000,
    downloads: '14M+',
    downloadsNote: '10M–50M Google Play installs. 14M+ across platforms per Uptodown data.',
    downloadsNum: 14000000,
    d1: 36,
    d7: 14,
    d30: 6.2,
    arpdau: 0.068,
    roas: 6.8,
    monetization: 'Hybrid (Balanced)',
    avgSession: 9.8,
    sessionsPerDay: 3.6,
    payerConversion: 4.1,
    arpu: 5.60,
    adRevenuePct: 55,
    iapRevenuePct: 45,
    topUserRevenue: 68,
    cpiByChannel: [
      { channel: 'Facebook (iOS)', cpi: 5.20, ltv: 7.40, roas: 1.42 },
      { channel: 'Google (Android)', cpi: 0.72, ltv: 3.20, roas: 4.44 },
      { channel: 'TikTok', cpi: 2.10, ltv: 4.00, roas: 1.90 },
      { channel: 'Organic', cpi: 0, ltv: 6.80, roas: 0 },
    ],
    retentionCurve: [
      { day: 0, rate: 100 }, { day: 1, rate: 36 }, { day: 3, rate: 22 },
      { day: 7, rate: 14 }, { day: 14, rate: 9.0 }, { day: 30, rate: 6.2 },
    ],
    cohortHeatmap: [
      [100, 36, 22, 14, 9.0, 6.2],
      [100, 37, 23, 15, 9.5, 6.5],
      [100, 35, 21, 13, 8.5, 5.9],
      [100, 38, 24, 16, 10.0, 6.8],
      [100, 34, 20, 13, 8.2, 5.7],
      [100, 36, 22, 14, 9.0, 6.2],
    ],
    levelFunnel: [
      { level: 'Install', users: 100 },
      { level: 'L5', users: 72 },
      { level: 'L10', users: 50 },
      { level: 'L20', users: 30 },
    ],
    insights: {
      acquisition: 'Highest LTV in portfolio at $7.40 (iOS/Facebook) due to daily content mechanic driving habitual engagement. Premium CPI justified by strong returns.',
      retention: 'Best D30 retention in portfolio (6.2%). Daily theme mechanic creates habitual return behavior — 27% above portfolio average D30.',
      engagement: 'Longest avg session (9.8 min) in portfolio. Content freshness is the primary engagement driver. High completion rates through L10.',
      monetization: 'Most balanced ad/IAP split (55/45). Hint pack bundles driving strong conversion. Less whale-dependent revenue distribution (top 10% = 68%).',
    },
  },
  {
    id: 'word-search-explorer',
    name: 'Word Search Explorer',
    category: 'Word Search',
    icon: '🔍',
    color: '#10b981',
    revenue: '$168K/day (~$56M/yr)',
    revenueNote: 'Estimated $168K/day in ad revenue (~$56M annually). IAP monetization delayed until after L24.',
    revenueNum: 56000000,
    downloads: '10M+',
    downloadsNote: 'Google Play 10M+ installs. Rapid growth title in PlaySimple portfolio.',
    downloadsNum: 12000000,
    d1: 30,
    d7: 10,
    d30: 4.2,
    arpdau: 0.045,
    roas: 4.8,
    monetization: 'Ad-First (IAP after L24)',
    avgSession: 6.5,
    sessionsPerDay: 2.4,
    payerConversion: 1.5,
    arpu: 2.40,
    adRevenuePct: 88,
    iapRevenuePct: 12,
    topUserRevenue: 84,
    cpiByChannel: [
      { channel: 'Facebook (iOS)', cpi: 4.20, ltv: 3.80, roas: 0.90 },
      { channel: 'Google (Android)', cpi: 0.55, ltv: 2.60, roas: 4.73 },
      { channel: 'TikTok', cpi: 1.50, ltv: 2.80, roas: 1.87 },
      { channel: 'Organic', cpi: 0, ltv: 4.20, roas: 0 },
    ],
    retentionCurve: [
      { day: 0, rate: 100 }, { day: 1, rate: 30 }, { day: 3, rate: 15 },
      { day: 7, rate: 10 }, { day: 14, rate: 5.8 }, { day: 30, rate: 4.2 },
    ],
    cohortHeatmap: [
      [100, 30, 15, 10, 5.8, 4.2],
      [100, 31, 16, 11, 6.2, 4.5],
      [100, 29, 14, 9, 5.4, 3.9],
      [100, 32, 17, 11, 6.5, 4.7],
      [100, 28, 13, 9, 5.1, 3.7],
      [100, 30, 15, 10, 5.8, 4.2],
    ],
    levelFunnel: [
      { level: 'Install', users: 100 },
      { level: 'L5', users: 55 },
      { level: 'L10', users: 30 },
      { level: 'L20', users: 14 },
    ],
    insights: {
      acquisition: 'Facebook iOS CPI ($4.20) exceeding LTV ($3.80) — ROAS below breakeven on iOS paid. Android and TikTok channels profitable.',
      retention: 'D1 at 30% at lower end of word game benchmarks. Delayed IAP may reduce early engagement incentives. Content repetitiveness identified as churn driver.',
      engagement: 'Shortest sessions in portfolio (6.5 min). IAP monetization delayed until L24, meaning most churned users never encounter purchase opportunities.',
      monetization: 'Highest ad revenue share in portfolio (88%). $56M est. annual ad revenue makes it the portfolio revenue leader. IAP penetration opportunity post-L24.',
    },
  },
  {
    id: 'wordwars',
    name: 'WordWars',
    category: 'PvP Word Game',
    icon: '⚔️',
    color: '#ef4444',
    revenue: '$120K/mo (US est.)',
    revenueNote: 'Estimated from portfolio share. PvP mechanic drives higher IAP conversion.',
    revenueNum: 1440000,
    downloads: '5M+',
    downloadsNote: 'Google Play installs. Smaller but highly engaged user base due to PvP format.',
    downloadsNum: 5000000,
    d1: 35,
    d7: 13,
    d30: 5.8,
    arpdau: 0.058,
    roas: 6.2,
    monetization: 'IAP-Heavy',
    avgSession: 9.4,
    sessionsPerDay: 3.4,
    payerConversion: 3.8,
    arpu: 5.20,
    adRevenuePct: 32,
    iapRevenuePct: 68,
    topUserRevenue: 79,
    cpiByChannel: [
      { channel: 'Facebook (iOS)', cpi: 5.00, ltv: 6.80, roas: 1.36 },
      { channel: 'Google (Android)', cpi: 0.70, ltv: 3.50, roas: 5.00 },
      { channel: 'TikTok', cpi: 2.00, ltv: 3.80, roas: 1.90 },
      { channel: 'Organic', cpi: 0, ltv: 6.20, roas: 0 },
    ],
    retentionCurve: [
      { day: 0, rate: 100 }, { day: 1, rate: 35 }, { day: 3, rate: 20 },
      { day: 7, rate: 13 }, { day: 14, rate: 8.5 }, { day: 30, rate: 5.8 },
    ],
    cohortHeatmap: [
      [100, 35, 20, 13, 8.5, 5.8],
      [100, 36, 21, 14, 9.0, 6.1],
      [100, 34, 19, 12, 8.0, 5.5],
      [100, 37, 22, 15, 9.5, 6.4],
      [100, 33, 18, 12, 7.8, 5.3],
      [100, 35, 20, 13, 8.5, 5.8],
    ],
    levelFunnel: [
      { level: 'Install', users: 100 },
      { level: 'L5', users: 68 },
      { level: 'L10', users: 45 },
      { level: 'L20', users: 25 },
    ],
    insights: {
      acquisition: 'PvP mechanic drives strong organic acquisition (~30% of installs organic). Social competition reduces dependency on paid channels.',
      retention: 'D30 at 5.8% — second-best retention in portfolio. Social/competitive loops sustain engagement beyond initial content consumption.',
      engagement: 'Highest sessions/day (3.4) driven by PvP competitive loops. Tournament events likely boost engagement by 30–40%.',
      monetization: 'IAP-dominant (68%) with strongest payer conversion (3.8%). Season pass and competitive advantage items drive purchases.',
    },
  },
  {
    id: 'crossword-explorer',
    name: 'Crossword Explorer',
    category: 'Crossword',
    icon: '🧩',
    color: '#f59e0b',
    revenue: '$90K/mo (US est.)',
    revenueNote: 'Localization efforts contributed to Q4 2024 growth (MTG earnings). Cross-promo opportunity with Daily Themed Crossword.',
    revenueNum: 1080000,
    downloads: '5M+',
    downloadsNote: 'Google Play installs. Growing through localization of Crossword Jam variant.',
    downloadsNum: 6000000,
    d1: 32,
    d7: 11,
    d30: 4.5,
    arpdau: 0.048,
    roas: 5.0,
    monetization: 'Hybrid',
    avgSession: 7.8,
    sessionsPerDay: 2.6,
    payerConversion: 2.5,
    arpu: 3.40,
    adRevenuePct: 62,
    iapRevenuePct: 38,
    topUserRevenue: 74,
    cpiByChannel: [
      { channel: 'Facebook (iOS)', cpi: 4.60, ltv: 4.40, roas: 0.96 },
      { channel: 'Google (Android)', cpi: 0.60, ltv: 2.50, roas: 4.17 },
      { channel: 'TikTok', cpi: 1.65, ltv: 3.00, roas: 1.82 },
      { channel: 'Organic', cpi: 0, ltv: 5.00, roas: 0 },
    ],
    retentionCurve: [
      { day: 0, rate: 100 }, { day: 1, rate: 32 }, { day: 3, rate: 17 },
      { day: 7, rate: 11 }, { day: 14, rate: 6.5 }, { day: 30, rate: 4.5 },
    ],
    cohortHeatmap: [
      [100, 32, 17, 11, 6.5, 4.5],
      [100, 33, 18, 12, 7.0, 4.8],
      [100, 31, 16, 10, 6.0, 4.2],
      [100, 34, 19, 12, 7.2, 5.0],
      [100, 30, 15, 10, 5.8, 4.0],
      [100, 32, 17, 11, 6.5, 4.5],
    ],
    levelFunnel: [
      { level: 'Install', users: 100 },
      { level: 'L5', users: 60 },
      { level: 'L10', users: 35 },
      { level: 'L20', users: 16 },
    ],
    insights: {
      acquisition: 'Facebook iOS CPI ($4.60) near-breakeven with LTV ($4.40). Growth opportunity through cross-promotion from Daily Themed Crossword user base.',
      retention: 'D1 at 32% slightly below portfolio average. Localization of Crossword Jam variant driving new market growth (MTG Q4 2024 earnings).',
      engagement: 'Completion rates drop significantly after L8. Difficulty progression optimization could improve mid-funnel retention.',
      monetization: 'Balanced hybrid model. Bundle pricing optimization could lift ARPU by 15–20% based on category benchmarks.',
    },
  },
];

export const strategicDiagnosis = {
  primaryConstraint: 'Retention',
  reasoning: [
    'Portfolio D30 retention averaging 5.4% — at benchmark but leaves room for improvement vs top 25% performers (7%+)',
    'Word game franchise revenue grew 17% YoY in constant currencies (MTG FY2025 earnings)',
    'Early lifecycle churn (D1→D3 losing ~50% of retained users) represents the largest growth constraint',
    'iOS CPI averaging $4.83 (Liftoff 2024) requires strong D7+ retention to achieve positive ROAS',
  ],
  priorities: [
    {
      title: 'Onboarding Optimization Experiment',
      description: 'A/B test streamlined tutorial flows to improve D1→D3 retention curve across all 6 titles',
      impact: 'High',
      effort: 'Medium',
    },
    {
      title: 'Word Search Explorer IAP Acceleration',
      description: 'Test earlier IAP placement (pre-L24) in Word Search Explorer to capture revenue from users who churn before L24',
      impact: 'High',
      effort: 'Low',
    },
    {
      title: 'Cross-Portfolio Promotion Engine',
      description: 'Leverage Daily Themed Crossword\'s 14M+ users to cross-promote Crossword Explorer and Word Trip',
      impact: 'Medium',
      effort: 'Medium',
    },
  ],
  expectedLift: '+12–18%',
};

export const growthSimulatorDefaults = {
  d1RetentionBoost: 0,
  payerConversionCurrent: 3.0,
  payerConversionNew: 3.0,
};

export const interviewDefense = [
  {
    question: 'Why simulate instead of use real data?',
    answer: 'PlaySimple\'s internal metrics are proprietary and NDA-protected. This dashboard uses publicly available data from Sensor Tower, MTG investor reports (FY2024: $233M revenue, 17% YoY growth), Liftoff CPI benchmarks, and AppsFlyer retention benchmarks. It demonstrates analytical thinking with real-world grounding.',
  },
  {
    question: 'How were benchmarks chosen?',
    answer: 'Revenue data from Sensor Tower estimates and MTG quarterly earnings. Retention benchmarks from AppsFlyer Q1 2024 (D1: 34%, D7: 12%, D30: 5.35% for puzzle games) and GameAnalytics. CPI data from Liftoff 2024 Casual Gaming Report (iOS: $4.83, Android: $0.65). Word Search Explorer ad revenue ($168K/day) from industry analysis.',
  },
  {
    question: 'How would you productionize this?',
    answer: 'Connect to data warehouse via REST/GraphQL API, implement real-time data refresh pipelines, add RBAC for team-specific views, KPI anomaly alerting via PagerDuty/Slack, and integrate with A/B testing platforms (Optimizely/Firebase) for experiment tracking.',
  },
  {
    question: 'How would this integrate with data warehouse?',
    answer: 'ETL pipelines from Firebase/Adjust/AppsFlyer into BigQuery, with dbt transformations creating analytics-ready tables. Dashboard queries hit materialized views for sub-second loads. Real-time streaming via Pub/Sub for live metrics.',
  },
  {
    question: 'How would this help product teams prioritize?',
    answer: 'By surfacing constraint-based insights (not just metrics), teams identify highest-leverage growth levers. Example: Word Search Explorer\'s $56M ad revenue with delayed IAP suggests immediate IAP experiment opportunity. The simulator enables quantitative impact estimation before committing resources.',
  },
];

export const cohortLabels = ['D0', 'D1', 'D3', 'D7', 'D14', 'D30'];
export const cohortWeeks = ['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6'];

export const dataSources = [
  'Sensor Tower (app revenue & download estimates)',
  'MTG AB Q4 2024 & FY2025 Earnings Reports',
  'Tracxn (PlaySimple FY2024 revenue: ₹1,930Cr / $233M)',
  'Liftoff 2024 Casual Gaming Report (CPI benchmarks)',
  'AppsFlyer Q1 2024 Retention Benchmarks',
  'GameAnalytics 2024 Mobile Gaming Benchmarks',
  'Industry estimates for Word Search Explorer ad revenue',
];
